name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
          release-type: node
          package-name: reconciler
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
